name: ipyautoui-dev
# channels priority
# see https://bioconda.github.io/
# conda-forge has highest prioriy
channels:
  - defaults
  - conda-forge
dependencies:
  - python
  - jupyterlab>=4.0.0,<5.0.0a0
  - jupyterlab-unfold
  - jupyterlab-lsp
  - python-lsp-server
  - jupytext
  - black
  - nb_black
  - pytest
  - altair # optional
  - halo # optional
  - plotly # optional
  - pip
  - pip:
    - maplocal==0.2.1
    - pydantic-extra-types
    - pytest-examples
    - jsonref
    - -e .