name: ipyautoui-dev
# channels priority
# see https://bioconda.github.io/
# conda-forge has highest prioriy
channels:
  - defaults
  - conda-forge
dependencies:
  - python
  - numpy
  - pandas
  - jupyterlab>=4.0.0,<5.0.0a0
  - jupyterlab-lsp
  - python-lsp-server
  - ipywidgets>8
  - ipyfilechooser
  - ipydatagrid
  - ipyvuetify
  - voila
  - plotly
  - halo
  - jupytext
  - markdown
  - nodejs
  - altair
  - pydantic>2
  - pydantic-settings
  - python-dotenv
  - pyyaml
  - openpyxl
  - black
  - nb_black
  - immutables
  - wcmatch
  - pytest
  - stringcase
  - pip
  - pip:
    - maplocal==0.1.1
    - pydantic-extra-types
    - pytest-examples
    - jsonref