name: ipyautoui-docs
# channels priority
# see https://bioconda.github.io/
# conda-forge has highest prioriy
# -
# jg notes
# -
# - needs everything that ipyautoui needs + everything for docs
# - in future when packaged could make ipyautoui a dependency
#   - in CI just make sure packaging happens first
channels:
  - conda-forge
dependencies:
  - python>=3.7
  - pandas
  - jupyterlab>4
  - ipywidgets
  - ipyfilechooser
  - ipydatagrid
  - ipyvuetify
  - voila
  - plotly
  - halo
  - jupytext
  - markdown
  - nodejs
  - altair
  - pydantic>2
  - pydantic-settings
  - stringcase
  - pyyaml
  - pillow
  - openpyxl
  - black
  - nb_black
  - immutables
  - wcmatch
  - jupyter-book # for docs
  - sphinx # for docs
  - sphinx-book-theme # for docs
  - sphinx-autoapi
  - autodoc-pydantic # for docs
  - nbsphinx-link
  - sphinxcontrib-mermaid
  - sphinx-panels
  - pytest
  - pip
  - pip:
    - maplocal==0.1.1
    - pytest-sphinx
    - jsonref
    - pydantic-extra-types
