name: ipyautoui-docs
# channels priority
# see https://bioconda.github.io/
# conda-forge has highest prioriy
channels:
  - defaults
  - conda-forge
dependencies:
  - python
  - jupyterlab>=4.0.0,<5.0.0a0
  - jupyterlab-unfold
  - jupyterlab-lsp
  - jupyterlab-myst
  - python-lsp-server
  - voila
  - voici
  - jupytext
  - black
  - nb_black
  - pytest
  - altair # optional
  - halo # optional
  - plotly # optional
  - jupyter-book # for docs
  - sphinx # for docs
  - sphinx-book-theme # for docs
  - sphinx-autoapi
  - autodoc-pydantic # for docs
  - nbsphinx-link
  - sphinxcontrib-mermaid
  - sphinx-panels
  - pip
  - pip:
    - maplocal==0.2.1
    - pydantic-extra-types
    - pytest-examples
    - -e ..