name: ipyautoui
# channels priority
# see https://bioconda.github.io/
# conda-forge has highest prioriy
channels:
  - defaults
  - conda-forge
#  - http://10.10.30.125:8000
dependencies:
  - python>=3.7
  - numpy
  - pandas
  - jupyterlab>=3.0.14
  - jupyterlab-unfold
  - xeus-python
  - ipywidgets
  - ipyfilechooser
  - ipydatagrid
  - ipyvuetify
  - voila>=0.2.11
  - plotly
  - halo
  - jupytext
  - markdown
  - nodejs
  - altair
  - pydantic
  - dacite
  - pyyaml
  - openpyxl
  - black
  - nb_black
  - immutables
  - wcmatch
  - pytest
  - pip
  - pip:
      - maplocal==0.1.1
