name: deploy-book

# Only run this when the master branch changes
on:
  push:
    branches:
    - main
    # If your git repository has the Jupyter Book within some-subfolder next to
    # unrelated files, you can make this run only if a file within that specific
    # folder has been modified.
    #
    # paths:
    # - some-subfolder/**

# This job installs dependencies, builds the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            label: linux-64
            prefix: /usr/share/miniconda3/envs/ipyautoui-dev

          # Add macOS and Windows builds here if you need them
          # - os: macos-latest
          #   label: osx-64
          #   prefix: /Users/runner/miniconda3/envs/ipyautoui-dev

          # - os: windows-latest
          #   label: win-64
          #   prefix: C:\Miniconda3\envs\ipyautoui-dev

    name: ${{ matrix.label }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup Mambaforge
        uses: conda-incubator/setup-miniconda@v2
        with:
            miniforge-variant: Mambaforge
            miniforge-version: latest
            activate-environment: ipyautoui-dev
            use-mamba: true

      - name: Set cache date
        run: echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - uses: actions/cache@v2
        with:
          path: ${{ matrix.prefix }}
          key: ${{ matrix.label }}-conda-${{ hashFiles('docs/environment.yml') }}-${{ env.DATE }}-${{ env.CACHE_NUMBER }}
        id: cache

      - name: Update environment
        run: mamba env update -n ipyautoui-dev -f docs/environment.yml
        if: steps.cache.outputs.cache-hit != 'true'
           
      - name: setup jb config
        shell: bash -l {0}
        run: jupyter-book config sphinx .

      - name: Build the book
        shell: bash -l {0}
        run: sphinx-build . _build/html -b html
          
      # Push the book's HTML to github-pages
      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v3.6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html
